pipeline {
    agent any

    stages {
        stage('Front End Deployment') {
            steps {
                script {
                    // Call the API to get the token
                    def token = sh(script: '''
                        aws eks get-token --cluster-name my-eks-cluster --query 'status.token' --output text
                    ''', returnStdout: true).trim()

                    // Store the token as a temporary secret
                    withEnv(["TOKEN=${token}"]) {

                        sh '''
                            set +x
                            kubectl config set-credentials eks-user --token=$TOKEN
                            aws eks update-kubeconfig --region ap-southeast-1 --name my-eks-cluster
                            kubectl config set-context --current --user=eks-user
                            set -x
                        '''
                    }
                }
            }
        }
    }
}
